import { DM_Sans } from 'next/font/google';
import "./globals.css";


const dm_sans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})


export const metadata = {
  title: "Crazy application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${dm_sans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
